version: 1
name: routely-local
dashboard:
  port: 3030
apps:
  - name: web
    type: app
    preset: custom
    driver: command
    path: /home/ruddypp/Documents/work/routely/examples/hello-command
    dev: PORT=3101 ROUTELY_EXAMPLE_NAME=web ROUTELY_EXAMPLE_ROLE=frontend npm run
      dev
    port: 3101
    healthcheck:
      path: /health
      expected_status: 200
  - name: worker
    type: app
    preset: custom
    driver: command
    path: /home/ruddypp/Documents/work/routely/examples/hello-command
    dev: PORT=3103 ROUTELY_EXAMPLE_NAME=worker ROUTELY_EXAMPLE_ROLE=worker npm run
      dev
    port: 3103
    healthcheck:
      path: /health
      expected_status: 200
  - name: api
    type: app
    preset: custom
    driver: command
    path: /home/ruddypp/Documents/work/routely/examples/hello-command
    dev: PORT=3102 ROUTELY_EXAMPLE_NAME=api ROUTELY_EXAMPLE_ROLE=api npm run dev
    port: 3102
    healthcheck:
      path: /health
      expected_status: 200
services:
  - name: postgres
    type: database
    preset: postgres
    driver: compose
    port: 5432
    env:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: app
    image: postgres:16
    internal: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
